project:
  type: book

book:
  title: "Introdução à Linha de Comando"
  author: "Julia Apolonio & João Cavalcante"
  chapters:
    - index.qmd
    - 01_Manipulando_arquivos.qmd
    - 02_Fluxos_de_dados.qmd
    - 03_Scripts_e_loops.qmd
    - 04_Ferramentas_adicionais.qmd
    - references.qmd

bibliography: references.bib


toc: true
number-sections: true

knitr:
  opts_chunk:
    message: false
    warning: false
    results: false

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

